# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unsigned_name', models.CharField(max_length=200)),
                ('order_sort', models.IntegerField()),
                ('public', models.CharField(choices=[('1', 'True'), ('0', 'False')], default=0, max_length=1)),
                ('meta_desc', models.CharField(max_length=120)),
                ('meta_key', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('public', models.FileField(choices=[('1', 'True'), ('0', 'False')], default=1, max_length=1, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('unsigned_title', models.CharField(max_length=250)),
                ('excerpt', models.TextField()),
                ('image', models.ImageField(upload_to='posts/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('view', models.IntegerField(default=0, verbose_name='View')),
                ('highlight', models.CharField(choices=[('1', 'True'), ('0', 'False')], default=0, max_length=1)),
                ('public', models.CharField(choices=[('1', 'Public'), ('0', 'Private')], default=1, max_length=1)),
                ('show_group', models.IntegerField(default=0)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog', verbose_name='Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unsigned_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posts', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
